// This file is auto-generated by keycloakify's `update-kc-gen` and regenerated
// on every build. Committed as an initial stub so `tsc` succeeds before the
// first `keycloakify build` call.
/* eslint-disable */
// @ts-nocheck

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "asunset";
export const themeNames: ThemeName[] = ["asunset"];
export type KcEnvName = never;
export const kcEnvNames: KcEnvName[] = [];
export const kcEnvDefaults: Record<KcEnvName, string> = {};

export type KcContext = import("./login/KcContext").KcContext;

declare global {
  interface Window {
    kcContext?: KcContext;
  }
}

export const KcLoginPage = lazy(() => import("./login/KcPage"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
  const { kcContext, fallback } = props;
  return (
    <Suspense fallback={fallback}>
      {(() => {
        switch (kcContext.themeType) {
          case "login":
            return <KcLoginPage kcContext={kcContext} />;
        }
      })()}
    </Suspense>
  );
}

export const BASE_URL = import.meta.env.BASE_URL;
