package main

// All generator templates live here as Go string constants. text/template
// executes against a Config. Keep each template tight and well-commented
// — operators read these after the wizard writes them.

const envTemplate = `# Generated by asunset-deploy. Edit by hand only if you know what you're doing —
# rerunning the wizard overwrites this file.
ASUNSET_ENV={{if .IsTLS}}prod{{else}}dev{{end}}
# ASUNSET_MODE is read by the CLI to pick the right compose overlay for
# lifecycle commands (up/down/logs/...). Do not hand-edit — re-run
# "asunset init" to change deployment mode.
ASUNSET_MODE={{.Mode}}

# ---- postgres (shared instance; three logical DBs) ----
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_SUPERUSER=postgres
POSTGRES_SUPERUSER_PASSWORD={{.Secrets.PostgresSuperPass}}

APP_DB_NAME=asunset
APP_DB_OWNER=asunset_owner
APP_DB_OWNER_PASSWORD={{.Secrets.AppOwnerPass}}
APP_DB_USER=asunset
APP_DB_PASSWORD={{.Secrets.AppUserPass}}

KC_DB_NAME=keycloak
KC_DB_USER=keycloak
KC_DB_PASSWORD={{.Secrets.KcDbPass}}

FGA_DB_NAME=openfga
FGA_DB_USER=openfga
FGA_DB_PASSWORD={{.Secrets.FgaDbPass}}

# ---- keycloak ----
KEYCLOAK_ADMIN={{.Secrets.KeycloakAdmin}}
KEYCLOAK_ADMIN_PASSWORD={{.Secrets.KeycloakAdminPass}}
KEYCLOAK_REALM=asunset
KEYCLOAK_PUBLIC_URL={{.AuthURL}}
KEYCLOAK_INTERNAL_URL={{.KeycloakInternalURL}}
KEYCLOAK_API_CLIENT_ID=asunset-api
KEYCLOAK_API_CLIENT_SECRET={{.Secrets.KeycloakAPISecret}}
KEYCLOAK_WEB_CLIENT_ID=asunset-web

# ---- openfga ----
OPENFGA_API_URL=http://openfga:8080
OPENFGA_STORE_NAME=asunset
OPENFGA_API_KEY={{.Secrets.OpenFGAAPIKey}}

# ---- api ----
API_PORT=8000
API_CORS_ORIGINS={{.WebURL}}
API_LOG_LEVEL=info

# ---- web ----
WEB_PORT=3000
VITE_API_URL={{.APIURL}}
VITE_KEYCLOAK_URL={{.AuthURL}}
VITE_KEYCLOAK_REALM=asunset
VITE_KEYCLOAK_CLIENT_ID=asunset-web
{{if .IsTLS}}
# ---- TLS mode (active when running with compose.tls.yml) ----
TLS_WEB_HOST={{.WebHost}}
TLS_AUTH_HOST={{.AuthHost}}
TLS_API_HOST={{.APIHost}}
{{end}}{{if .IsTailscale}}
# ---- Tailscale mode (active when running with compose.tailscale.yml) ----
# Tailscale serve on the host proxies :443 -> caddy:5173, giving us
# MagicDNS-issued TLS for free. Inside the compose network everything
# stays plain HTTP and path-multiplexed by Caddy.
TAILSCALE_HOST={{.TailscaleHost}}
{{end}}
# ---- vector / audit pipeline ----
VECTOR_LOG_LEVEL=info

# ---- email: Keycloak SMTP (auth flows) ----
# Set KC_SMTP_HOST to enable Keycloak's own mail (verify-email,
# forgot-password, magic-link invite). Empty disables Keycloak mail
# entirely. Resend: host=smtp.resend.com, port=587, user=resend,
# password=<api key>, starttls=true.
KC_SMTP_HOST=
KC_SMTP_PORT=587
KC_SMTP_USER=
KC_SMTP_PASSWORD=
KC_SMTP_FROM=
KC_SMTP_FROM_DISPLAY_NAME=
KC_SMTP_REPLY_TO=
KC_SMTP_STARTTLS=true
KC_SMTP_SSL=false
KC_SMTP_AUTH=true

# ---- email: app-side notifier (product flows) ----
# Backend = log (dev) or resend (prod). Switch to resend + set
# RESEND_API_KEY for real delivery. Different sender than Keycloak's
# on purpose — noreply@<domain> vs noreply-auth@<domain>.
NOTIFIER_BACKEND=log
RESEND_API_KEY=
NOTIFIER_DEFAULT_SENDER=noreply@asunset.local
NOTIFIER_DEFAULT_LOCALE=en
NOTIFIER_TEMPLATE_DIR=

# ---- invites: how new-user credentials are bootstrapped ----
# magic_link    KC emails a one-time set-password link (needs KC SMTP).
# temp_password Backend returns a temp password admin shares out-of-band.
#               Use when outbound SMTP is blocked (Linode, etc.).
# auto          magic_link first, fall back to temp_password on failure.
INVITE_DELIVERY=magic_link
`

const caddyInternalTemplate = `# Generated by asunset-deploy (tls-internal mode).
# Caddy's internal CA signs the certs. Browsers warn until you trust the CA.
#
# To fetch + install the root CA on Linux:
#   docker compose -f compose.yml -f compose.tls.yml exec caddy \
#     cat /data/caddy/pki/authorities/local/root.crt | sudo tee /usr/local/share/ca-certificates/caddy-root.crt
#   sudo update-ca-certificates

{
    local_certs
    email {{if .AcmeEmail}}{{.AcmeEmail}}{{else}}ops@example.com{{end}}
}

{{.WebHost}} {
    encode zstd gzip
    reverse_proxy web:80
    header {
        Strict-Transport-Security "max-age=63072000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
        X-Frame-Options "DENY"
        -Server
    }
}

{{.AuthHost}} {
    encode zstd gzip
    reverse_proxy keycloak:8080
    header {
        Strict-Transport-Security "max-age=63072000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
        -Server
    }
}

{{.APIHost}} {
    encode zstd gzip
    reverse_proxy api:8000
    header {
        Strict-Transport-Security "max-age=63072000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
        -Server
    }
}
`

const caddyOperatorTemplate = `# Generated by asunset-deploy (tls-operator mode).
# Cert + key are mounted from the host into Caddy via compose.tls.yml.

{WebHost} {
    encode zstd gzip
    tls {CertPath} {KeyPath}
    reverse_proxy web:80
    header {
        Strict-Transport-Security "max-age=63072000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
        X-Frame-Options "DENY"
        -Server
    }
}

{AuthHost} {
    encode zstd gzip
    tls {CertPath} {KeyPath}
    reverse_proxy keycloak:8080
    header {
        Strict-Transport-Security "max-age=63072000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
        -Server
    }
}

{APIHost} {
    encode zstd gzip
    tls {CertPath} {KeyPath}
    reverse_proxy api:8000
    header {
        Strict-Transport-Security "max-age=63072000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
        -Server
    }
}
`

const caddyAcmeTemplate = `# Generated by asunset-deploy (tls-acme mode).
# Caddy auto-issues + renews via Let's Encrypt. Requires ports 80 + 443
# reachable from ACME validation servers.

{
    email {AcmeEmail}
}

{WebHost} {
    encode zstd gzip
    reverse_proxy web:80
    header {
        Strict-Transport-Security "max-age=63072000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
        X-Frame-Options "DENY"
        -Server
    }
}

{AuthHost} {
    encode zstd gzip
    reverse_proxy keycloak:8080
    header {
        Strict-Transport-Security "max-age=63072000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
        -Server
    }
}

{APIHost} {
    encode zstd gzip
    reverse_proxy api:8000
    header {
        Strict-Transport-Security "max-age=63072000; includeSubDomains"
        X-Content-Type-Options "nosniff"
        Referrer-Policy "strict-origin-when-cross-origin"
        -Server
    }
}
`

const caddyTailscaleTemplate = `# Generated by asunset-deploy (tailscale mode).
# Caddy listens on plain HTTP and lets Tailscale serve terminate TLS
# externally. One hostname, path-multiplexed.
#
# Tailscale-injected identity headers (Tailscale-User-Login, -Name,
# -Profile-Pic) are preserved end-to-end so future integrations can
# consult them.

:5173 {
    encode zstd gzip

    # Preserve the /auth prefix; Keycloak runs with
    # --http-relative-path=/auth so every KC URL includes it.
    handle /auth/* {
        reverse_proxy keycloak:8080
    }

    # Strip /api so FastAPI routes see the unprefixed path.
    handle_path /api/* {
        reverse_proxy api:8000
    }

    # Everything else: the SPA.
    handle {
        reverse_proxy web:80
    }

    log {
        output stdout
        format console
    }
}
`
